
service: aws-iam-sleuth


provider:
  name: aws
  region: us-west-2
  deploymentBucket: transcom-ppp-serverless-sleuth
  runtime: python3.6

  # Uncomment below if serverless to handle IAM
  # iamRoleStatements:
  #   - Effect: 'Allow'
  #     Action:
  #       - "iam:DeleteAccessKey"
  #       - "iam:UpdateAccessKey"
  #       - "iam:ListAccessKeys"
  #       - "iam:ListUsers"
  #     Resource: '*'
  #   - Effect: 'Allow'
  #     Action:
  #       - "ssm:GetParameter"
  #     Resource: '*'


functions:
  iam-sleuth:
    handler: sleuth/handler.handler
    memorySize: 256
    role: "arn:aws:iam::923914045601:role/serverless_sleuth"
    # events:
    #   - schedule:
    #       name: Test_event
    #       description: Just a test event
    #       rate: rate(60 minutes)
    #       enabled: true

package:
  # python doesn't need node_modules
  exclude:
    - .pre-commit*/**
    - node_modules/**
    - .pytest_cache/**
    - tests/**
    - .venv/**

custom:
  pythonRequirements:
    fileName: build/requirements.txt
    dockerizePip: non-linux
    zip: true
    slim: true
    invalidateCaches: true

plugins:
  - serverless-python-requirements
