
service: aws-iam-sleuth


provider:
  name: aws
  runtime: python3.6


functions:
  iam-sleuth:
    handler: sleuth/handler.handler
    memorySize: 256
    events:
      - schedule:
          name: Test_event
          description: Just a test event
          rate: rate(60 minutes)
          enabled: true

package:
  # python doesn't need node_modules
  exclude:
    - .pre-commit*/**
    - node_modules/**
    - .pytest_cache/**
    - tests/**
    - .venv/**

custom:
  pythonRequirements:
    dockerizePip: non-linux
    zip: true

plugins:
  - serverless-python-requirements
