
service: aws-iam-sleuth


provider:
  name: aws
  region: us-west-2
  deploymentBucket: transcom-ppp-serverless-sleuth
  runtime: python3.6

  # Uncomment below if serverless to handle IAM
  # iamRoleStatements:
  #   - Effect: 'Allow'
  #     Action:
  #       - "iam:DeleteAccessKey"
  #       - "iam:UpdateAccessKey"
  #       - "iam:ListAccessKeys"
  #       - "iam:ListUsers"
  #     Resource: '*'
  #   - Effect: 'Allow'
  #     Action:
  #       - "ssm:GetParameter"
  #     Resource: '*'


functions:
  iam-sleuth:
    name: iam-sleuth
    handler: sleuth/handler.handler
    memorySize: 256
    timeout: 600 # set high incase of high IAM account count
    role: "arn:aws:iam::923914045601:role/serverless_sleuth"
    environment:
      SNS_TOPIC: arn:aws:sns:us-west-2:923914045601:slack-events
      #SLACK_URL: <YOUR URL HERE>
    events:
      - schedule:
          name: DailyCheck
          description: Runs MON-FRI at 18:00 UTC for daily auditing.
          rate: 'cron(0 18 ? * MON-FRI *)'
          enabled: true

package:
  # python doesn't need node_modules
  exclude:
    - .pre-commit*/**
    - node_modules/**
    - .pytest_cache/**
    - tests/**
    - .venv/**

custom:
  pythonRequirements:
    fileName: build/requirements.txt
    dockerizePip: non-linux
    zip: true
    slim: true
    invalidateCaches: true

plugins:
  - serverless-python-requirements
