version: 2.1

orbs:
  python: circleci/python@0.3.0

jobs:
  build-and-release:
    docker:
      - image: trussworks/circleci-docker-primary:ghr
    steps:
      - checkout
      - run:
          name: Build
          command: scripts/build
      - run:
          name: Release
          command: scripts/release
  python-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache:
          dependency-file: ./sleuth/requirements.txt
      - python/install-deps:
          dependency-file: ./sleuth/requirements.txt
      - python/save-cache:
          dependency-file: ./sleuth/requirements.txt
      - python/test:
          pytest: true

workflows:
  version: 2
  validate:
    jobs:
      - python-test
  release:
    jobs:
      - build-and-release:
          filters:
            branches:
              only: master
