version: 2.1

orbs:
  python: circleci/python@0.3.0

jobs:
  python-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache:
          dependency-file: ./sleuth/requirements.txt
      - python/install-deps:
          dependency-file: ./sleuth/requirements.txt
      - python/save-cache:
          dependency-file: ./sleuth/requirements.txt
      - python/test:
          pytest: true

workflows:
  version: 2
  validate:
    jobs:
      - python-test
