version: 2.1

orbs:
  python: circleci/python@0.3.2

jobs:
  build:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - run:
          name: Build
          command: scripts/build
  release:
    docker:
      - image: trussworks/ghr:391c83e041d5467164631f7e5be2fa00b46e14a7
    steps:
      - checkout
      - run:
          name: Build
          command: scripts/build
      - run:
          name: Release
          command: scripts/release $CIRCLE_PROJECT_USERNAME $CIRCLE_PROJECT_REPONAME << pipeline.git.tag >>
  validate:
    docker:
      - image: trussworks/circleci-docker-primary:e66fbea875bcb788b29b1b5f59142e8231961ec5
    steps:
      - checkout
      - restore_cache:
          keys:
            - pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
      - run:
          name: Run pre-commit tests
          command: pre-commit run --all-files
      - save_cache:
          key: pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - ~/.cache/pre-commit
  python-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache:
          dependency-file: ./sleuth/requirements.txt
          # The scheme here let's us bust the cache if python is upgraded or if we modify the requirements
          key: pip-3.8.5-{{ checksum "./sleuth/requirements.txt" }}
      - python/install-deps:
          dependency-file: ./sleuth/requirements.txt
      - python/save-cache:
          dependency-file: ./sleuth/requirements.txt
          key: pip-3.8.5-{{ checksum "./sleuth/requirements.txt" }}
      - python/test:
          pytest: true

workflows:
  version: 2
  validate:
    jobs:
      - validate
      - python-test
  release:
    jobs:
      - release
