version: 2.1

orbs:
  python: circleci/python@0.3.0

jobs:
  validate:
    docker:
      - image: trussworks/circleci-docker-primary:ffbfa3d3e13660c63ec50154a0323190825d1fb0
    steps:
      - checkout
      - restore_cache:
          keys:
            - pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
      - run:
          name: Run pre-commit tests
          command: pre-commit run --all-files
      - save_cache:
          key: pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - ~/.cache/pre-commit
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - command: pip install --upgrade pip
      - python/load-cache:
          dependency-file: ./sleuth/requirements.txt
      - python/install-deps:
          dependency-file: ./sleuth/requirements.txt
      - python/save-cache:
          dependency-file: ./sleuth/requirements.txt
      - run:
          command: |
            # pytest would be a dep in requirements.txt
            pytest ./sleuth/tests
          name: Test

workflows:
  version: 2
  validate:
    jobs:
      - validate
      - build-and-test
