version: 2.1

orbs:
  python: circleci/python@0.3.0

jobs:
  build-and-release:
    docker:
      - image: trussworks/circleci-docker-primary:ghr
    steps:
      - checkout
      - run:
          name: Build
          command: scripts/build
      - run:
          name: Release
          command: scripts/release
  validate:
    docker:
      - image: trussworks/circleci-docker-primary:e66fbea875bcb788b29b1b5f59142e8231961ec5
    steps:
      - checkout
      - restore_cache:
          keys:
            - pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
      - run:
          name: Run pre-commit tests
          command: pre-commit run --all-files
      - save_cache:
          key: pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - ~/.cache/pre-commit
  python-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache:
          dependency-file: ./sleuth/requirements.txt
      - python/install-deps:
          dependency-file: ./sleuth/requirements.txt
      - python/save-cache:
          dependency-file: ./sleuth/requirements.txt
      - python/test:
          pytest: true

workflows:
  version: 2
  validate:
    jobs:
      - validate
      - python-test
  release:
    jobs:
      - build-and-release:
          filters:
            branches:
              only: master
